// =============================================================================
// Metrics — dual-emission for FileGenerator.
//
// Every counter is published two ways:
//   1. prometheus-net: scraped at /metrics (existing surface; future managed
//      Prometheus scrape config).
//   2. System.Diagnostics.Metrics on a Meter named "F1.FileGenerator": picked
//      up by the Azure Monitor OpenTelemetry distro and shipped to App
//      Insights -> customMetrics. This is what the alerts in
//      infra/modules/monitoring.bicep query against.
//
// Use the Record* helpers (RecordFileGenerated, RecordSqlError,
// RecordCacheHit, RecordCacheMiss) instead of touching the raw counters so
// both sinks stay in sync.
// =============================================================================

using System.Diagnostics.Metrics;
using Prometheus;

namespace F1.FileGenerator;

public static class Metrics
{
    /// <summary>OpenTelemetry meter name. Must be registered in
    /// Program.cs via <c>.WithMetrics(b =&gt; b.AddMeter(Metrics.MeterName))</c>
    /// or App Insights will not see any of these instruments.</summary>
    public const string MeterName = "F1.FileGenerator";

    private static readonly Meter OtelMeter = new(MeterName, "1.0.0");

    // ---------- OpenTelemetry instruments (-> App Insights customMetrics) ----
    private static readonly Counter<long> _otelFilesGenerated =
        OtelMeter.CreateCounter<long>("f1_files_generated", description: "Files generated by FileGenerator.");
    private static readonly Counter<long> _otelSqlErrors =
        OtelMeter.CreateCounter<long>("f1_filegen_sql_errors", description: "FileGenerator SQL errors.");
    private static readonly Counter<long> _otelCacheHits =
        OtelMeter.CreateCounter<long>("f1_filegen_cache_hits", description: "FileGenerator cache hits.");
    private static readonly Counter<long> _otelCacheMisses =
        OtelMeter.CreateCounter<long>("f1_filegen_cache_misses", description: "FileGenerator cache misses.");

    // ---------- prometheus-net counters (-> /metrics) ------------------------
    public static readonly Prometheus.Counter FilesGenerated = Prometheus.Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static readonly Prometheus.Counter SqlErrors = Prometheus.Metrics.CreateCounter(
        "f1_filegen_sql_errors_total",
        "FileGenerator SQL errors.",
        new CounterConfiguration { LabelNames = new[] { "endpoint" } });

    public static readonly Prometheus.Counter CacheHits = Prometheus.Metrics.CreateCounter(
        "f1_filegen_cache_hits_total",
        "FileGenerator cache hits.",
        new CounterConfiguration { LabelNames = new[] { "endpoint" } });

    public static readonly Prometheus.Counter CacheMisses = Prometheus.Metrics.CreateCounter(
        "f1_filegen_cache_misses_total",
        "FileGenerator cache misses.",
        new CounterConfiguration { LabelNames = new[] { "endpoint" } });

    // ---------- helpers (use these) ------------------------------------------
    public static void RecordFileGenerated(string endpoint, string format)
    {
        FilesGenerated.WithLabels(endpoint, format).Inc();
        _otelFilesGenerated.Add(1,
            new KeyValuePair<string, object?>("endpoint", endpoint),
            new KeyValuePair<string, object?>("format", format));
    }

    public static void RecordSqlError(string endpoint)
    {
        SqlErrors.WithLabels(endpoint).Inc();
        _otelSqlErrors.Add(1, new KeyValuePair<string, object?>("endpoint", endpoint));
    }

    public static void RecordCacheHit(string endpoint)
    {
        CacheHits.WithLabels(endpoint).Inc();
        _otelCacheHits.Add(1, new KeyValuePair<string, object?>("endpoint", endpoint));
    }

    public static void RecordCacheMiss(string endpoint)
    {
        CacheMisses.WithLabels(endpoint).Inc();
        _otelCacheMisses.Add(1, new KeyValuePair<string, object?>("endpoint", endpoint));
    }
}
