// =============================================================================
// Metrics — shared Prometheus counters/histograms across endpoints.
// =============================================================================

using Prometheus;

namespace F1.FileGenerator;

public static class Metrics
{
    public static readonly Counter FilesGenerated = Prometheus.Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static readonly Counter SqlErrors = Prometheus.Metrics.CreateCounter(
        "f1_filegen_sql_errors_total",
        "FileGenerator SQL errors.",
        new CounterConfiguration { LabelNames = new[] { "endpoint" } });
}
