// =============================================================================
// /files/lap-detail  — telemetry samples for a single lap.
// =============================================================================

using System.Globalization;
using System.Text;
using Prometheus;

namespace F1.FileGenerator.Endpoints;

public static class LapDetailEndpoints
{
    private static readonly Counter FilesGenerated = Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static void Map(WebApplication app)
    {
        app.MapGet("/files/lap-detail", (int year, int round, string session,
            string driver, int lap, string format,
            ISqlConnectionFactory db, IFileCache cache) =>
        {
            format = (format ?? "json").ToLowerInvariant();
            if (format != "csv" && format != "json")
            {
                return Results.Problem(statusCode: 400, title: "format must be csv or json");
            }

            // TODO(spec §6): query SQL MI for telemetry samples for this lap.
            //   SELECT t.SampleTimeMs, t.SpeedKph, t.RPM, t.Throttle, t.Brake, t.Gear, t.DRS
            //   FROM dbo.Telemetry t
            //   JOIN dbo.Laps    l ON l.LapId = t.LapId
            //   JOIN dbo.Sessions s ON s.SessionId = l.SessionId
            //   JOIN dbo.Events   e ON e.EventId   = s.EventId
            //   JOIN dbo.Seasons  se ON se.SeasonId = e.SeasonId
            //   JOIN dbo.Drivers  d ON d.DriverId  = l.DriverId
            //   WHERE se.[Year] = @year AND e.Round = @round
            //     AND s.SessionType = @session AND d.Code = @driver AND l.LapNumber = @lap
            //   ORDER BY t.SampleTimeMs;

            FilesGenerated.WithLabels("lap-detail", format).Inc();

            // Synthesize ~10 sample points so the chart on the web tier renders.
            var samples = Enumerable.Range(0, 10).Select(i => new
            {
                sampleTimeMs = i * 100,
                speedKph = 200 + i * 5,
                rpm = 11000 + i * 50,
                throttle = (byte)(i < 5 ? 100 : 60),
                brake = i >= 8,
                gear = (byte)(i < 4 ? 7 : 6),
                drs = (byte)(i % 2)
            }).ToArray();

            if (format == "json")
            {
                return Results.Json(new { year, round, session, driver, lap, samples });
            }

            var sb = new StringBuilder();
            sb.AppendLine("SampleTimeMs,SpeedKph,RPM,Throttle,Brake,Gear,DRS");
            foreach (var s in samples)
            {
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "{0},{1},{2},{3},{4},{5},{6}",
                    s.sampleTimeMs, s.speedKph, s.rpm, s.throttle,
                    s.brake ? 1 : 0, s.gear, s.drs));
            }
            return Results.Text(sb.ToString(), "text/csv", Encoding.UTF8);
        })
        .WithName("GetLapDetail");
    }
}
