// =============================================================================
// /files/qualifying  — Q1/Q2/Q3 per driver, with delta-to-pole.
// =============================================================================

using System.Globalization;
using System.Text;
using Prometheus;

namespace F1.FileGenerator.Endpoints;

public static class QualifyingEndpoints
{
    private static readonly Counter FilesGenerated = Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static void Map(WebApplication app)
    {
        app.MapGet("/files/qualifying", (int year, int round, string format,
            ISqlConnectionFactory db, IFileCache cache) =>
        {
            format = (format ?? "csv").ToLowerInvariant();
            if (format != "csv" && format != "json")
            {
                return Results.Problem(statusCode: 400, title: "format must be csv or json");
            }

            // TODO(spec §6): query SQL MI for qualifying results.
            //   SELECT d.Code, d.FullName, d.TeamName, q.Position, q.Q1Ms, q.Q2Ms, q.Q3Ms
            //   FROM dbo.QualiResults q
            //   JOIN dbo.Sessions s ON s.SessionId = q.SessionId
            //   JOIN dbo.Events   e ON e.EventId   = s.EventId
            //   JOIN dbo.Seasons se ON se.SeasonId = e.SeasonId
            //   JOIN dbo.Drivers  d ON d.DriverId  = q.DriverId
            //   WHERE se.[Year] = @year AND e.Round = @round AND s.SessionType = 'Q'
            //   ORDER BY q.Position;

            FilesGenerated.WithLabels("qualifying", format).Inc();

            if (format == "csv")
            {
                var sb = new StringBuilder();
                sb.AppendLine("Year,Round,Position,Driver,Team,Q1Ms,Q2Ms,Q3Ms,DeltaToPoleMs");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "{0},{1},1,VER,Red Bull Racing,72112,71604,70901,0", year, round));
                return Results.Text(sb.ToString(), "text/csv", Encoding.UTF8);
            }

            return Results.Json(new
            {
                year, round,
                rows = new[]
                {
                    new { position = 1, driver = "VER", team = "Red Bull Racing",
                          q1Ms = 72112, q2Ms = 71604, q3Ms = 70901, deltaToPoleMs = 0 }
                }
            });
        })
        .WithName("GetQualifying");
    }
}
