// =============================================================================
// /files/race  — lap-by-lap race results (CSV or JSON).
// =============================================================================

using System.Globalization;
using System.Text;
using Prometheus;

namespace F1.FileGenerator.Endpoints;

public static class RaceEndpoints
{
    private static readonly Counter FilesGenerated = Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static void Map(WebApplication app)
    {
        app.MapGet("/files/race", async (int year, int round, string format,
            ISqlConnectionFactory db, IFileCache cache, CancellationToken ct) =>
        {
            format = (format ?? "csv").ToLowerInvariant();
            if (format != "csv" && format != "json")
            {
                return Results.Problem(statusCode: 400, title: "format must be csv or json");
            }

            // TODO(spec §6): query SQL MI for race results.
            //   SELECT d.Code, d.FullName, d.TeamName, l.LapNumber, l.LapTimeMs,
            //          l.Sector1Ms, l.Sector2Ms, l.Sector3Ms, l.Compound, l.Position
            //   FROM dbo.Sessions s
            //   JOIN dbo.Events  e ON e.EventId = s.EventId
            //   JOIN dbo.Seasons se ON se.SeasonId = e.SeasonId
            //   JOIN dbo.Laps    l ON l.SessionId = s.SessionId
            //   JOIN dbo.Drivers d ON d.DriverId = l.DriverId
            //   WHERE se.[Year] = @year AND e.Round = @round AND s.SessionType = 'R'
            //   ORDER BY l.LapNumber, l.Position
            //
            // Use cache.TryGetCachedPath() / cache.WriteAsync() per spec §5.2.

            FilesGenerated.WithLabels("race", format).Inc();

            if (format == "csv")
            {
                var csv = BuildPlaceholderCsv(year, round);
                return Results.Text(csv, "text/csv", Encoding.UTF8);
            }
            else
            {
                var rows = BuildPlaceholderJson(year, round);
                return Results.Json(rows);
            }
        })
        .WithName("GetRace");
    }

    private static string BuildPlaceholderCsv(int year, int round)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Year,Round,Driver,Team,Lap,LapTimeMs,Sector1Ms,Sector2Ms,Sector3Ms,Compound,Position");
        // One sample row so the web tier renders something on first load.
        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "{0},{1},VER,Red Bull Racing,1,76123,24011,30502,21610,MEDIUM,1", year, round));
        return sb.ToString();
    }

    private static object BuildPlaceholderJson(int year, int round) => new
    {
        year,
        round,
        rows = new[]
        {
            new
            {
                driver = "VER", team = "Red Bull Racing", lap = 1, lapTimeMs = 76123,
                sector1Ms = 24011, sector2Ms = 30502, sector3Ms = 21610,
                compound = "MEDIUM", position = 1
            }
        }
    };
}
