// =============================================================================
// /files/season  — event calendar with rounds, dates, locations.
// =============================================================================

using System.Globalization;
using System.Text;
using Prometheus;

namespace F1.FileGenerator.Endpoints;

public static class SeasonEndpoints
{
    private static readonly Counter FilesGenerated = Metrics.CreateCounter(
        "f1_files_generated_total",
        "Files generated by FileGenerator.",
        new CounterConfiguration { LabelNames = new[] { "endpoint", "format" } });

    public static void Map(WebApplication app)
    {
        app.MapGet("/files/season", (int year, string format,
            ISqlConnectionFactory db, IFileCache cache) =>
        {
            format = (format ?? "csv").ToLowerInvariant();
            if (format != "csv" && format != "json")
            {
                return Results.Problem(statusCode: 400, title: "format must be csv or json");
            }

            // TODO(spec §6): query SQL MI for the season calendar.
            //   SELECT e.Round, e.Country, e.Location, e.EventName, e.EventDate
            //   FROM dbo.Events e
            //   JOIN dbo.Seasons s ON s.SeasonId = e.SeasonId
            //   WHERE s.[Year] = @year
            //   ORDER BY e.Round;

            FilesGenerated.WithLabels("season", format).Inc();

            // Placeholder: one event so the season browser renders.
            var rows = new[]
            {
                new { round = 8, country = "Monaco", location = "Monte Carlo",
                      eventName = "Monaco Grand Prix", eventDate = "2024-05-26" }
            };

            if (format == "json") return Results.Json(new { year, rows });

            var sb = new StringBuilder();
            sb.AppendLine("Round,Country,Location,EventName,EventDate");
            foreach (var r in rows)
            {
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "{0},{1},{2},{3},{4}",
                    r.round, r.country, r.location, r.eventName, r.eventDate));
            }
            return Results.Text(sb.ToString(), "text/csv", Encoding.UTF8);
        })
        .WithName("GetSeason");
    }
}
